# -*- coding: utf-8 -*-
"""sspa.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dXGBoRTvhDtkQ8Gw_zpyT5u3P45x5Edv
"""

csv_data = """study_hours,sleep_hours,screen_time,attendance,marks
2,6,6,70,55
3,7,5,75,60
4,6,4,80,65
5,7,4,85,72
6,8,3,90,78
7,8,2,92,82
8,7,2,95,88
9,8,1,97,92"""

with open("data.csv", "w") as f:
    f.write(csv_data)

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns


df = pd.read_csv("data.csv")


print("DATASET:")
print(df)

print("\nSTATISTICS:")
print(df.describe())

print("\nCORRELATION:")
print(df.corr())


sns.pairplot(df)
plt.show()


plt.figure()
sns.heatmap(df.corr(), annot=True, cmap="coolwarm")
plt.title("Correlation Heatmap")
plt.show()


df["productivity"] = df["study_hours"] - df["screen_time"]


from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

X = df[["study_hours", "sleep_hours", "screen_time", "attendance"]]
y = df["marks"]

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=1
)

model = LinearRegression()
model.fit(X_train, y_train)

pred = model.predict(X_test)

print("\nPREDICTED:", pred)
print("ACTUAL:", y_test.values)
print("MODEL ACCURACY:", model.score(X_test, y_test))


!pip install streamlit

import streamlit as st
import pandas as pd
from sklearn.linear_model import LinearRegression


df = pd.read_csv("data.csv")

X = df[["study_hours", "sleep_hours", "screen_time", "attendance"]]
y = df["marks"]

model = LinearRegression()
model.fit(X, y)


st.title("Student Study Pattern Analyzer")

study = st.slider("Study Hours", 1, 10, 5)
sleep = st.slider("Sleep Hours", 4, 10, 7)
screen = st.slider("Screen Time", 0, 8, 3)
att = st.slider("Attendance (%)", 60, 100, 85)

pred = model.predict([[study, sleep, screen, att]])

st.subheader("Predicted Marks:")
st.success(int(pred[0]))
